modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="disableportal"
version="1.1"
displayName="DisablePortal"
authors="24na7"
description="This mod disables the ability to activate Nether or End portals. You can enable or disable this blocking feature and activate the portal."

[[dependencies.disableportal]]
   modId="forge"
   mandatory=true
   versionRange="47.3.0"
   ordering="NONE"
   side="BOTH"

[[dependencies.disableportal]]
   modId="minecraft"
   mandatory=true
   versionRange="1.20.1"
   ordering="NONE"
   side="BOTH"
